### ISSUE TITLE
[RESOLVED] download

### ISSUE THREAD

**Issue by kack-kun** [einstein95/crunchy-xml-decoder#114]
> Traceback (most recent call last):
>   File "C:\Users\kack\Desktop\CRip\crunchy-xml-decoder.py", line 369, in <module>
>     makechoise()
>   File "C:\Users\kack\Desktop\CRip\crunchy-xml-decoder.py", line 302, in makechoise
>     ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', '')
>   File "crunchy-xml-decoder\ultimate.py", line 293, in ultimate
>     video_hls(filen, video_input)
>   File "crunchy-xml-decoder\hls.py", line 111, in video_hls
>     fetch_encryption_key(video)
>   File "crunchy-xml-decoder\hls.py", line 94, in fetch_encryption_key
>     video.key.key_value = urllib2.urlopen(url = video.key.uri).read()
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 422, in _open
>     '_open', req)
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 1222, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 1184, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

pip freeze
iso8601==0.1.11
lxml==3.2.5
m3u8==0.2.10
pycrypto==2.6

**Comment by kack-kun** [comment]
sorry, lol
my python v2.7.5
