### ISSUE TITLE
Downloader will not mux together  Chain Chronicle - The Light of Haecceitas - TV version file

### ISSUE THREAD

**Issue by darkhelmet2016** [einstein95/crunchy-xml-decoder#118]
Traceback (most recent call last):
  File "C:\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 369, in <module>
    makechoise()
  File "C:\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 317, in makechoise
    queueu('.\\queue.txt')
  File "C:\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 106, in queueu
    ultimate.ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 289, in ultimate
    subtitles(title)
  File "crunchy-xml-decoder\ultimate.py", line 160, in subtitles
    sublangc = sub_id3.pop(0)
IndexError: pop from empty list
Press any key to continue . . .

**Comment by limitless-dev** [comment]
Can I have the link which you're trying to download?

**Comment by darkhelmet2016** [comment]
http://www.crunchyroll.com/chain-chronicle-the-light-of-haecceitas-/episode-1-the-light-of-haecceitas-728597

**Comment by limitless-dev** [comment]
It works without any problem.

**Comment by darkhelmet2016** [comment]
Not on my end. If it worked as you said I would not be posting the error.

**Comment by jsonn** [comment]
I can confirm that there are some shows where the list of subtitles is messed up. Haven't had a chance to work on a clean workaround yet.
