### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by 36gianni36** [einstein95/crunchy-xml-decoder#19]
Get this error message when downloading.
I honestly have no idea what's going on...
FLV is downloaded correctly (in HD and stuff)
But the sub is not.

Attempting to decrypt subtitles...
Success!  Subtitles decrypted.
Traceback (most recent call last):
  File "C:\Users\Gianni\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder\ultimate.py", line 210, in <module>
    shutil.move(title + '.flv', '.\export\\')
  File "C:\Python27\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: '.\\export\\'
****** Job completed successfully *****

**Comment by einstein95** [comment]
What video are you trying to download?
