### ISSUE TITLE
xml ??

### ISSUE THREAD

**Issue by alzamer2** [einstein95/crunchy-xml-decoder#6]
hi and thanks for the hard work
i download the last fix but i got this error:
Traceback (most recent call last):
  File "D:\C\mkv\+rip\crunchy-xml-decoder\crunchy-xml-decoder\crunchy-xml-decoder\ultimate.py", line 97, in <module>
    xmlconfig = BeautifulSoup(altfuncs.getxml('RpcApiVideoPlayer_GetStandardConfig', media_id), 'xml')
  File "D:\C\mkv\+rip\crunchy-xml-decoder\crunchy-xml-decoder\crunchy-xml-decoder\bs4\__init__.py", line 155, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

and changing lxml_32 or lxml_64 is not working is diffrent error

**Comment by MidgardSerpent** [comment]
replace the lxml files with one of the versions on this page https://pypi.python.org/pypi/lxml/3.2.5 (you can open the .exe file with winrar to extract it directly bypassing the installer)

**Comment by alzamer2** [comment]
thanks MidgardSerpent fixes
