### ISSUE TITLE
little pb with debian!

### ISSUE THREAD

**Issue by rcyclope** [einstein95/crunchy-xml-decoder#65]
```
--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth             it, and supports the animators.

----------
Booting up...

/bin/sh: 1: title: not found
/bin/sh: 1: title: not found
Downloading video...
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 8
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Download complete
Attempting to decrypt subtitles...
Success!  Subtitles decrypted.
Starting mkv merge
Traceback (most recent call last):
  File "crunchy-xml-decoder.py", line 354, in <module>
    makechoise()
  File "crunchy-xml-decoder.py", line 305, in makechoise
    makechoise()
  File "crunchy-xml-decoder.py", line 290, in makechoise
    ultimate.ultimate(raw_input('Please enter Crunchyroll video URL:\n'), '', ''             )
  File "crunchy-xml-decoder/ultimate.py", line 315, in ultimate
    subprocess.call(mkvcmd)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

i have changing a few line in "unltimate.py" and "crunchy-xml-decoder" to adapt the script  for linux
(.\\ =>./, rtmpdump.exe=>rtmpdump, mkvmerge.exe=> mkvmerg) installing mkvtoolkit and rtmpdump

**Comment by shinji257** [comment]
The version of rtmpdump on Linux doesn't support protocol 10 which is needed.  At this time I'm unaware of a binary of rtmpdump on linux that can do so.

**Comment by rcyclope** [comment]
i find my pb with mkvmerge
in ultimate.py i have suppr a piece of line and replace subprocess.call by os.system
and work it

`        312    mkvcmd='mkvmerge -o "./export/' + title + '[' + heightp.strip() +'].mkv" --language 0:jpn --language 1:jpn -a 1 -d 0 ' + '"./export/' + title + '.flv"' + subtitlefilecode +' --title "' + title +'"'
         313   #print mkvcmd
         314  #print subtitlefilecode
         315   os.system(mkvcmd)`
