### ISSUE TITLE
Error downloading dubbed content

### ISSUE THREAD

**Issue by stark700** [einstein95/crunchy-xml-decoder#68]
When processing a queue of dubbed videos, that have no subtitles, the downloader will give an error at the end of the first video and shut down

Download complete
Starting mkv merge
Traceback (most recent call last):
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 354, in <module>
    makechoise()
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 302, in makechoise
    queueu('.\\queue.txt')
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 94, in queueu
    ultimate.ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 284, in ultimate
    u'╪º┘ä╪╣╪▒╪¿┘è╪⌐': 'ara', u'Deutsch': 'deu'}[lang]
KeyError: '[English (US)]'
Press any key to continue . . .

**Comment by SuperrSonic** [comment]
I started running into this issue myself, it happens on titles without subs available, the code expects subs to mux in so it fails.
I just made it so that subs are ignored instead of a proper fix but it works well for me, I simply swap the files as needed.

[Download link](https://www.dropbox.com/s/nz2uwjm6fureear/CR_ultimate_fix.zip?dl=1); just keep both folders easily accessible, replace 'crunchy-xml-decoder/ultimate.py' when required.

**Comment by stark700** [comment]
Thanks for that! It's quite a hassle to have to manually go through a list of files one by one without that.

**Comment by stark700** [comment]
I have come across a different error with that now

Download complete
Traceback (most recent call last):
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 354, in <module>
    makechoise()
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 302, in makechoise
    queueu('.\\queue.txt')
  File "C:\Users\X\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.
py", line 94, in queueu
    ultimate.ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 271, in ultimate
    '62' : '720p', '80' : '1080p', '0' : 'highest'}[xmlconfig.find('video_encode
_quality').string]
KeyError: u'30'
Press any key to continue . . .

**Comment by SuperrSonic** [comment]
Excuse the delay, this looks just like the error here in https://github.com/einstein95/crunchy-xml-decoder/issues/60, I've updated the link with Kamekameha's fix, just download again and see if it's related.

**Comment by stark700** [comment]
It seems that you were right, I downloaded the decode and ultimate file from kamekameha and it got me up to the same error I listed in my first post.

Which line(s) did you edit from Ultimate? Sorry, I'm not used to doing this stuff. I think if I use his decode & ultimate file with your fix, it will be fine.

**Comment by SuperrSonic** [comment]
The link in my first reply has been updated simply download it again.

**Comment by stark700** [comment]
That works! Thanks a bunch.

**Comment by darkhelmet2016** [comment]
Still get the error if the video has hard sub in the video and soft sub in other languages.

File "crunchy-xml-decoder\ultimate.py", line 292, in ultimate
    if sublangc == sublang:
NameError: global name 'sublang' is not defined
Press any key to continue . . .

**Comment by darkhelmet2016** [comment]
http://www.crunchyroll.com/brotherhood-final-fantasy-xv The episodes here are English hard subbed, but still contain subs for other languages, so it still expects to be able to locate subs in the Crunchyroll code for the other languages present or the file will not mux for mkv output.

**Comment by SuperrSonic** [comment]
I was able to mux fine, that error only shows up if you use the burned_ultimate.py, this is exclusively for videos that lack soft subs so this error is expected, works fine if you use the regular one.

**Comment by darkhelmet2016** [comment]
I got an error message that begs to differ, it only muxes if you have the other subs added to the file, but if you do not want those subs in it and have the ini file set to Eng for the primary and secondary it will not mux. I do not want Spanish, or Arabic or any other subs in the file. 

Traceback (most recent call last):
  File "C:\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 354, in <module>
    makechoise()
  File "C:\Users\Wilson\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 302, in makechoise
    queueu('.\\queue.txt')
  File "C:\Users\Wilson\Desktop\crunchy-xml-decoder-master\crunchy-xml-decoder.p
y", line 94, in queueu
    ultimate.ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 283, in ultimate
KeyError: '[English (US)]'
Press any key to continue . . .

**Comment by SuperrSonic** [comment]
Oh, I just thought you weren't able to download at all. Since this is a completely different behaviour from other videos I don't think I can do much, I added to the dl link an extra ultimate.py which should work for those videos. Still makes the subs, but only muxes video and audio.

**Comment by darkhelmet2016** [comment]
Thanks for the reply, but yea the video still will download just fine but it will not hash out to verify completeness because it still tries to look for one of the non hard subbed non English tracks for mkv merge, but because the English sub flag is absent it will not mux properly unless you tell it to look for one of the other subtitled tracks in the url. The video will still mux as long as you set the primary or fall back to another track like Arabic, it just has to be taken back out again if your player can only handle one sub track.
