### ISSUE TITLE
Error during "Crypto Extracting" during initial start?

### ISSUE THREAD

**Issue by Truanifan** [einstein95/crunchy-xml-decoder#97]
I've no idea what I'm doing wrong... I have Python and pycrypto installed so I've no idea how to fix it.

Here's the error I get when I start the bat file:
```
python version=2.7.1 32 bit
OS Version=Windows 7 6.1.7601 SP1
System Type=AMD64
Crypto installed
lxml not installed
Downloading link:https://pypi.python.org/packages/2.7/l/lxml/lxml-3.2.5.win32-py
2.7.exe#md5=00536d2ff2b5e9e0b221a936b6fff169
100% [......................................................] 3179751 / 3179751
Crypto Extracting.....
Traceback (most recent call last):
  File "C:\Users\...\Downloads\crunchy-xml-decoder-master\crunchy-xml-decoder.py", line 9, in <module>
    import functtest
  File "crunchy-xml-decoder\functtest.py", line 102, in <module>
    unzip_('.\\temp\\crypto.exe','.\\temp\\')
  File "crunchy-xml-decoder\functtest.py", line 12, in unzip_
    zf = zipfile.ZipFile(filename_)
  File "C:\Python27\lib\zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '.\\temp\\crypto.exe'
Press any key to continue . . .
```

Also, I'm not great at Windows... How do I run the "pip" thing to install the m3u8 bit when I come to that step?

Thanks in advance.

**Comment by Aeryax** [comment]
Hello,

You should try to install lxml with the binary:
[https://pypi.python.org/pypi/lxml/3.2.5](https://pypi.python.org/pypi/lxml/3.2.5)

**Comment by Truanifan** [comment]
That fixed my problem. I ran into having to install m3u8 0.2.10 manually, but after I did so everything worked perfectly. Thanks!
